# render.yaml
services:
  - type: web
    name: tu-app-supabase
    env: static
    buildCommand: |
      npm install -g replace-in-file
      replace-in-file "__GOOGLE_API_KEY__" "$GOOGLE_API_KEY" ./materia.js
      replace-in-file "__GOOGLE_CLIENT_ID__" "$GOOGLE_CLIENT_ID" ./materia.js
      # Si también tienes estas claves en app.js, añade:
      # replace-in-file "__GOOGLE_API_KEY__" "$GOOGLE_API_KEY" ./app.js
      # replace-in-file "__GOOGLE_CLIENT_ID__" "$GOOGLE_CLIENT_ID" ./app.js
    startCommand: |
      # Render no necesita un comando de inicio especial para HTML/JS estático.
      # Si tienes un servidor, lo pondrías aquí. Para estático, puede ser vacío o simplemente un "exit 0".
      echo "Servicio estático listo."
      exit 0
    staticPublishPath: . # Publica todo el directorio raíz
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: SUPABASE_URL # Asegúrate de tener estas también si no están
        sync: false
      - key: SUPABASE_KEY
        sync: false
